DATA_PATH: 'data/'
EMBEDDINGS: 'sentence-transformers/all-MiniLM-L6-v2'
WEAVIATE_HOST: 'http://localhost'
WEAVIATE_PORT: 8080
WEAVIATE_EMBEDDING_DIM: 384
MODEL_BIN_PATH: 'models/llama-2-13b-chat.Q5_K_M.gguf'
USE_GPU: False
PRE_PROCESSOR_SPLIT_LENGTH: 1000
PRE_PROCESSOR_SPLIT_OVERLAP: 0
PROMPT_ANSWER_MAX_LENGTH_TOKENS: 1000
MODEL_MAX_TOKEN_LIMIT: 1048